var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    o   o   o                   ",
   "                                         o o                                xx  ",
   "  xx                                               xxxxxxxxxxx               x  ",
   "  x                                     xxxxx      x!!!!!!!!!x               x  ",
   "  x                                                x   v v   x             o x  ",
   "  x          xxxx                                                            x  ",
   "  x  @       x  x     o o                                                    x  ",
   "  xxxxxxxxxxxx  xxxxx     xxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                    x&&&&&x   x~~~x                  x     x                    ",
   "                    x&&&&&x   x~~~x                  x!!!!!x                    ",
   "                    xxxxxxx   xxxxx                  x!!!!!x                    ",
   "                                                     xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                           o   o                                                  ",
   "                                                                                                                  ",
   "                                                          xxxxxxx                                                 ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                       xxxx        x                                              ",
   "                                                       x           x                                              ",
   "                                                       x           x                                              ",
   "                                                       x        xxxx                                              ",
   "                                                       x           x                                              ",
   "                         o o                           x           x                                              ",
   "                                                       xxxx        x                                              ",
   "                        xxxxx                          x           x                                              ",
   "               o o                                     x           x                                              ",
   "                               xx     xx               x        xxxx                                              ",
   "              xxxxx            xx     xx               x           x                              xxxxxxx         ",
   "                               xx     xx               x           x                                    x         ",
   "      @                        xx     xx               xxxx        x                                    x         ",
   "     xxx             xxx       xx     xx               x           x                                    x         ",
   "    xxxxx                      xx     xx               x           x  xxxxxxxxxxxx                      x         ",
   "    x   x      xx              xx     xx               x        xxxx  x!!!!!!!!!!x                      x         ",
   "&&&&x   x&&&&&&x               xx     xx!!!!!!!!!!!!!!!x           x  x!!!!!!!!!!x                 o  o x         ",
   "&&&&x   x&&&&&&x    x~~~x      xx     xx!!!!!!!!!!!!!!!x           x  x  v    v  x                      x         ",
   "&&&&x   x&&&&&&x    x~~~x      xx      xxxxxxxxxxxxxxxxxxxx        x!!x          x                xxxxxxx         ",
   "&&&&x   x&&&&&&x    xxxxx      xx                                  xxxx          x                x               ",
   "&&&&x   x&&&&&&x               xx                                                                 x               ",
   "&&&&x   x&&&&&&x!!!!!!!!!!!!!!!xx                                                                 x               ",
   "&&&&x   x&&&&&&x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                       ~                                      ",
   "                                                   o    o       o  o       o  o       o  o                    ",
   "                                                                                                              ",
   "                                                  xxxxxxxx     xxxxxx     xxxxxx     xxxxxx                   ",
   "                                                 xxx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                 xxx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                 xxx    xx     xx  xx     xx  xx     xx  xx                   ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx               xx  ",
   "                                                  xx    xx     xx  xx     xx  xx     xx  xx               xx  ",
   "                                           xxxxxxxxx    xx     xx  xx     xx  xx     xx  xx!!!!!!!!!!!!!!!xx  ",
   "                                  o  o                  xx     xx  xx     xx  xx     xx  xx!!!!!!!!!!!!!!!xx  ",
   "                                                        xx     xx  xx     xx  xx     xx  xxxxxxxxxxxxxxxxxxx  ",
   "                                 xxxxxx                 xx     xx  xx     xx  xx!!!!!xx                       ",
   "  xxxx               xxxxx                              xx     xx  xx     xx  xx!!!!!xx                 xxxx  ",
   "  x                                                     xx     xx  xx     xx  xxxxxxxxx                    x  ",
   "  x                                                     xx     xx  xx     xxxxxxxxxxxxxxxxxxxxxx           x  ",
   "  x           xxxxx                                     xx     xx  xx     xx o  o =o  o =o  o xx       o   x  ",
   "  x                                                     xx     xx  xx                                      x  ",
   "  x    xxxx               xxx                           xx     xx  xx                                  o   x  ",
   "  x                       x                             xx     xx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x  ",
   "  x           @           x                           xxx       xxx                                 xxxxxxxx  ",
   "  x    xxxxxxxxxx      xxxx                         xxx           xxx                               x         ",
   "  x~~~~x        x&&&&&&x                                                                            x         ",
   "  x~~~~x        x&&&&&&x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "  xxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                    &     &                                                                   ",
   "                                     &   &                        &               &               &           ",
   "                                      & &    &&&&   &   &          &             &   &            &           ",
   "                                       &    &    &  &   &           &     &     &        &        &           ",
   "                                       &    &    &  &   &            &   & &   &     &   &&&&&    &           ",
   "                                       &    &    &  &   &             & &   & &      &   &   &                ",
   "                                       &     &&&&    &&&               &     &       &   &   &    &           ",
   "                         xxx                                                                                  ",
   "                        xx xx                                                                                 ",
   "  x                    xx   xx                                                                           xx   ",
   "  x                   xx     xx                                                                          xx   ",
   "  x  @               xx       xx                                                                         xx   ",
   "  xxxxxxxx          xx         xx                                                                     o  xx   ",
   "         xx        xx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "          xx      xx                                                                                          ",
   "           xxxxxxxx                                                                                           ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
